debug: true
local: true
restapi:
  probe_host: "0.0.0.0"
  probe_port: "18000"
  graphql_host: "localhost"
  graphql_port: "18080"
grpc:
  logger_host: "localhost"
  logger_port: "18081"
  user_host: "localhost"
  user_port: "18082"
  dlr_host: "localhost"
  dlr_port: "18083"
  authentication_host: "localhost"
  authentication_port: "18084"