// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package book

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookSvcClient is the client API for BookSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookSvcClient interface {
	GetPagesByFilter(ctx context.Context, in *PageFilter, opts ...grpc.CallOption) (*Pages, error)
	CreatePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error)
	DeletePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error)
	UpdatePageBase(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error)
	UpdatePageCore(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error)
	UpdatePageStatus(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error)
}

type bookSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewBookSvcClient(cc grpc.ClientConnInterface) BookSvcClient {
	return &bookSvcClient{cc}
}

func (c *bookSvcClient) GetPagesByFilter(ctx context.Context, in *PageFilter, opts ...grpc.CallOption) (*Pages, error) {
	out := new(Pages)
	err := c.cc.Invoke(ctx, "/BookSvc/GetPagesByFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookSvcClient) CreatePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/BookSvc/CreatePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookSvcClient) DeletePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/BookSvc/DeletePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookSvcClient) UpdatePageBase(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/BookSvc/UpdatePageBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookSvcClient) UpdatePageCore(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/BookSvc/UpdatePageCore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookSvcClient) UpdatePageStatus(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/BookSvc/UpdatePageStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookSvcServer is the server API for BookSvc service.
// All implementations must embed UnimplementedBookSvcServer
// for forward compatibility
type BookSvcServer interface {
	GetPagesByFilter(context.Context, *PageFilter) (*Pages, error)
	CreatePage(context.Context, *Page) (*Page, error)
	DeletePage(context.Context, *Page) (*Page, error)
	UpdatePageBase(context.Context, *Page) (*Page, error)
	UpdatePageCore(context.Context, *Page) (*Page, error)
	UpdatePageStatus(context.Context, *Page) (*Page, error)
	mustEmbedUnimplementedBookSvcServer()
}

// UnimplementedBookSvcServer must be embedded to have forward compatible implementations.
type UnimplementedBookSvcServer struct {
}

func (UnimplementedBookSvcServer) GetPagesByFilter(context.Context, *PageFilter) (*Pages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPagesByFilter not implemented")
}
func (UnimplementedBookSvcServer) CreatePage(context.Context, *Page) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePage not implemented")
}
func (UnimplementedBookSvcServer) DeletePage(context.Context, *Page) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePage not implemented")
}
func (UnimplementedBookSvcServer) UpdatePageBase(context.Context, *Page) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePageBase not implemented")
}
func (UnimplementedBookSvcServer) UpdatePageCore(context.Context, *Page) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePageCore not implemented")
}
func (UnimplementedBookSvcServer) UpdatePageStatus(context.Context, *Page) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePageStatus not implemented")
}
func (UnimplementedBookSvcServer) mustEmbedUnimplementedBookSvcServer() {}

// UnsafeBookSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookSvcServer will
// result in compilation errors.
type UnsafeBookSvcServer interface {
	mustEmbedUnimplementedBookSvcServer()
}

func RegisterBookSvcServer(s grpc.ServiceRegistrar, srv BookSvcServer) {
	s.RegisterService(&BookSvc_ServiceDesc, srv)
}

func _BookSvc_GetPagesByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookSvcServer).GetPagesByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookSvc/GetPagesByFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookSvcServer).GetPagesByFilter(ctx, req.(*PageFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookSvc_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookSvcServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookSvc/CreatePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookSvcServer).CreatePage(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookSvc_DeletePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookSvcServer).DeletePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookSvc/DeletePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookSvcServer).DeletePage(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookSvc_UpdatePageBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookSvcServer).UpdatePageBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookSvc/UpdatePageBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookSvcServer).UpdatePageBase(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookSvc_UpdatePageCore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookSvcServer).UpdatePageCore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookSvc/UpdatePageCore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookSvcServer).UpdatePageCore(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookSvc_UpdatePageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookSvcServer).UpdatePageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookSvc/UpdatePageStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookSvcServer).UpdatePageStatus(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

// BookSvc_ServiceDesc is the grpc.ServiceDesc for BookSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BookSvc",
	HandlerType: (*BookSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPagesByFilter",
			Handler:    _BookSvc_GetPagesByFilter_Handler,
		},
		{
			MethodName: "CreatePage",
			Handler:    _BookSvc_CreatePage_Handler,
		},
		{
			MethodName: "DeletePage",
			Handler:    _BookSvc_DeletePage_Handler,
		},
		{
			MethodName: "UpdatePageBase",
			Handler:    _BookSvc_UpdatePageBase_Handler,
		},
		{
			MethodName: "UpdatePageCore",
			Handler:    _BookSvc_UpdatePageCore_Handler,
		},
		{
			MethodName: "UpdatePageStatus",
			Handler:    _BookSvc_UpdatePageStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
